const suggestions = [
    { "id": "AI", "text": "Artificial Intelligence" },
    { "id": "CS", "text": "Computer Science" },
    { "id": "IT", "text": "Information Technology" },
    { "id": "DS", "text": "Data Science" },
    { "id": "ML", "text": "Machine Learning" },
    { "id": "CY", "text": "Cybersecurity" },
    { "id": "CN", "text": "Computer Networks" },
    { "id": "DBMS", "text": "Database Management System" },
    { "id": "OS", "text": "Operating Systems" },
    { "id": "SE", "text": "Software Engineering" },
    { "id": "WD", "text": "Web Development" },
    { "id": "MD", "text": "Mobile Development" },
    { "id": "ES", "text": "Embedded Systems" },
    { "id": "R", "text": "Robotics" },
    { "id": "GD", "text": "Game Development" },
    { "id": "MT", "text": "Multimedia Technology" },
    { "id": "BT", "text": "Blockchain Technology" },
    { "id": "AR", "text": "Augmented Reality" },
    { "id": "VR", "text": "Virtual Reality" },
    { "id": "CC", "text": "Cloud Computing" },
    { "id": "DM", "text": "Data Mining" },
    { "id": "N", "text": "Networking" },
    { "id": "C", "text": "Cryptography" },
    { "id": "M", "text": "Mathematics" },
    { "id": "L", "text": "Logic" },
    { "id": "ML", "text": "Mathematical Logic" },
    { "id": "FL", "text": "Fuzzy Logic" },
    { "id": "ST", "text": "Set Theory" },
    { "id": "PT", "text": "Proof Theory" },
    { "id": "MT", "text": "Model Theory" },
    { "id": "RT", "text": "Recursion Theory" },
    { "id": "TT", "text": "Type Theory" },
    { "id": "CT", "text": "Category Theory" },
    { "id": "FM", "text": "Formal Methods" },
    { "id": "AT", "text": "Automata Theory" },
    { "id": "CT", "text": "Complexity Theory" },
    { "id": "IT", "text": "Information Theory" },
    { "id": "GT", "text": "Game Theory" },
    { "id": "DT", "text": "Decision Theory" },
    { "id": "NLP", "text": "Natural Language Processing" },
    { "id": "CV", "text": "Computer Vision" },
    { "id": "DL", "text": "Deep Learning" },
    { "id": "RL", "text": "Reinforcement Learning" },
    { "id": "QC", "text": "Quantum Computing" },
    { "id": "DA", "text": "Data Analysis" },
    { "id": "BI", "text": "Business Intelligence" },
    { "id": "HCI", "text": "Human-Computer Interaction" },
    { "id": "IOT", "text": "Internet of Things" },
    { "id": "DSA", "text": "Data Structures and Algorithms" },
    { "id": "PP", "text": "Parallel Programming" },
    { "id": "DP", "text": "Distributed Systems" },
    { "id": "TS", "text": "Theoretical Computer Science" },
    { "id": "OPT", "text": "Optimization" },
    { "id": "CP", "text": "Computational Physics" },
    { "id": "CM", "text": "Computational Mathematics" }
];


export default suggestions;
