const suggestions = [
        { "id": "AI", "text": "Artificial Intelligence" },
        { "id": "CS", "text": "Computer Science" },
        { "id": "IT", "text": "Information Technology" },
        { "id": "DS", "text": "Data Science" },
        { "id": "ML", "text": "Machine Learning" },
        { "id": "BI", "text": "Bioinformatics" },
        { "id": "CAD", "text": "Computer Aided Design" },
        { "id": "CY", "text": "Cybersecurity" },
        { "id": "CN", "text": "Computer Networks" },
        { "id": "DBMS", "text": "Database Management System" },
        { "id": "OS", "text": "Operating Systems" },
        { "id": "SE", "text": "Software Engineering" },
        { "id": "WD", "text": "Web Development" },
        { "id": "MD", "text": "Mobile Development" },
        { "id": "ES", "text": "Embedded Systems" },
        { "id": "R", "text": "Robotics" },
        { "id": "GD", "text": "Game Development" },
        { "id": "MT", "text": "Multimedia Technology" },
        { "id": "BT", "text": "Blockchain Technology" },
        { "id": "AR", "text": "Augmented Reality" },
        { "id": "VR", "text": "Virtual Reality" },
        { "id": "CC", "text": "Cloud Computing" },
        { "id": "DM", "text": "Data Mining" },
        { "id": "N", "text": "Networking" },
        { "id": "C", "text": "Cryptography" },
        { "id": "P", "text": "Physics" },
        { "id": "CH", "text": "Chemistry" },
        { "id": "B", "text": "Biology" },
        { "id": "M", "text": "Mathematics" },
        { "id": "A", "text": "Astrophysics" },
        { "id": "G", "text": "Geology" },
        { "id": "ES", "text": "Environmental Science" },
        { "id": "N", "text": "Neuroscience" },
        { "id": "P", "text": "Psychology" },
        { "id": "MS", "text": "Materials Science" },
        { "id": "A", "text": "Astronomy" },
        { "id": "O", "text": "Oceanography" },
        { "id": "M", "text": "Meteorology" },
        { "id": "E", "text": "Ecology" },
        { "id": "G", "text": "Genetics" },
        { "id": "I", "text": "Immunology" },
        { "id": "P", "text": "Pharmacology" },
        { "id": "B", "text": "Biochemistry" },
        { "id": "B", "text": "Biophysics" },
        { "id": "QP", "text": "Quantum Physics" },
        { "id": "N", "text": "Nanotechnology" },
        { "id": "CS", "text": "Cognitive Science" },
        { "id": "FS", "text": "Forensic Science" },
        { "id": "A", "text": "Anthropology" },
        { "id": "A", "text": "Archaeology" },
        { "id": "L", "text": "Logic" },
        { "id": "ML", "text": "Mathematical Logic" },
        { "id": "ML", "text": "Modal Logic" },
        { "id": "TL", "text": "Temporal Logic" },
        { "id": "IL", "text": "Intuitionistic Logic" },
        { "id": "FL", "text": "Fuzzy Logic" },
        { "id": "PL", "text": "Philosophical Logic" },
        { "id": "ST", "text": "Set Theory" },
        { "id": "PT", "text": "Proof Theory" },
        { "id": "MT", "text": "Model Theory" },
        { "id": "RT", "text": "Recursion Theory" },
        { "id": "TT", "text": "Type Theory" },
        { "id": "CT", "text": "Category Theory" },
        { "id": "FM", "text": "Formal Methods" },
        { "id": "AT", "text": "Automata Theory" },
        { "id": "CT", "text": "Complexity Theory" },
        { "id": "IT", "text": "Information Theory" },
        { "id": "GT", "text": "Game Theory" },
        { "id": "DT", "text": "Decision Theory" },
        { "id": "POS", "text": "Philosophy of Science" },
        { "id": "HOS", "text": "History of Science" }
    ];
    
    export default suggestions;
    