const suggestions = [
        { "id": 1, "text": "Artificial Intelligence" },
        { "id": 2, "text": "Computer Science" },
        { "id": 3, "text": "Information Technology" },
        { "id": 4, "text": "Data Science" },
        { "id": 5, "text": "Machine Learning" },
        { "id": 6, "text": "Bioinformatics" },
        { "id": 7, "text": "Computer Aided Design" },
        { "id": 8, "text": "Cybersecurity" },
        { "id": 9, "text": "Computer Networks" },
        { "id": 10, "text": "Database Management System" },
        { "id": 11, "text": "Operating Systems" },
        { "id": 12, "text": "Software Engineering" },
        { "id": 13, "text": "Web Development" },
        { "id": 14, "text": "Mobile Development" },
        { "id": 15, "text": "Embedded Systems" },
        { "id": 16, "text": "Robotics" },
        { "id": 17, "text": "Game Development" },
        { "id": 18, "text": "Multimedia Technology" },
        { "id": 19, "text": "Blockchain Technology" },
        { "id": 20, "text": "Augmented Reality" },
        { "id": 21, "text": "Virtual Reality" },
        { "id": 22, "text": "Cloud Computing" },
        { "id": 23, "text": "Data Mining" },
        { "id": 24, "text": "Networking" },
        { "id": 25, "text": "Cryptography" },
        { "id": 26, "text": "Physics" },
        { "id": 27, "text": "Chemistry" },
        { "id": 28, "text": "Biology" },
        { "id": 29, "text": "Mathematics" },
        { "id": 30, "text": "Astrophysics" },
        { "id": 31, "text": "Geology" },
        { "id": 32, "text": "Environmental Science" },
        { "id": 33, "text": "Neuroscience" },
        { "id": 34, "text": "Psychology" },
        { "id": 35, "text": "Materials Science" },
        { "id": 36, "text": "Astronomy" },
        { "id": 37, "text": "Oceanography" },
        { "id": 38, "text": "Meteorology" },
        { "id": 39, "text": "Ecology" },
        { "id": 40, "text": "Genetics" },
        { "id": 41, "text": "Immunology" },
        { "id": 42, "text": "Pharmacology" },
        { "id": 43, "text": "Biochemistry" },
        { "id": 44, "text": "Biophysics" },
        { "id": 45, "text": "Quantum Physics" },
        { "id": 46, "text": "Nanotechnology" },
        { "id": 47, "text": "Cognitive Science" },
        { "id": 48, "text": "Forensic Science" },
        { "id": 49, "text": "Anthropology" },
        { "id": 50, "text": "Archaeology" },
        { "id": 51, "text": "Logic" },
        { "id": 52, "text": "Mathematical Logic" },
        { "id": 53, "text": "Modal Logic" },
        { "id": 54, "text": "Temporal Logic" },
        { "id": 55, "text": "Intuitionistic Logic" },
        { "id": 56, "text": "Fuzzy Logic" },
        { "id": 57, "text": "Philosophical Logic" },
        { "id": 58, "text": "Set Theory" },
        { "id": 59, "text": "Proof Theory" },
        { "id": 60, "text": "Model Theory" },
        { "id": 61, "text": "Recursion Theory" },
        { "id": 62, "text": "Type Theory" },
        { "id": 63, "text": "Category Theory" },
        { "id": 64, "text": "Formal Methods" },
        { "id": 65, "text": "Automata Theory" },
        { "id": 66, "text": "Complexity Theory" },
        { "id": 67, "text": "Information Theory" },
        { "id": 68, "text": "Game Theory" },
        { "id": 69, "text": "Decision Theory" },
        { "id": 70, "text": "Philosophy of Science" },
        { "id": 71, "text": "History of Science" }
];

export default suggestions;
