version: '3.8'

services:

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./conf/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server
      - client
    networks:
      - my-network

  client:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: client
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      my-network:
        aliases:
          - client

  server:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: server
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --chdir /var/www/backend/src app:app
    volumes:
      - ./backend:/var/www/backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      my-network:
        aliases:
          - server

networks:
  my-network:
