version: '3.8'

services:
  client:
    container_name: aicongressclient
    build:
      context: ../client
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ../client:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    networks:
      - server
    environment:
      - CI=true

  api:
    container_name: aicongressapi
    build: ../server/.
    restart: always
    volumes:
      - ../server:/app
    working_dir: /app
    env_file: ../server/.env
    environment:
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
      - TZ=Europe/Madrid

    ports:
      - 5000:5000
    networks:
      - server
    command: "flask run --host=0.0.0.0"

  mongodb:
    container_name: aicongressdb
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    env_file: ../server/.env
    networks:
      - server

  

  
volumes:
  mongodata:

networks:
  server:
    driver: bridge



  # client:
  #   build:
  #     context: ../client
  #     dockerfile: Dockerfile
  #   container_name: client
  #   command: npm start
  #   volumes:
  #     - ../client:/usr/app
  #     - /usr/app/node_modules
  #   ports:
  #     - "3000:3000"
