version: '3.8'

services:

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      #- ./frontend/build:/usr/share/nginx/html
      - ../:/var/www
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - server
      - client
    networks:
      - my-network

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: client
    command: npm start
    volumes:
      - ../client:/usr/app
      - /usr/app/node_modules
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      my-network:
        aliases:
          - client

  server:
    build:
      context: ../
      dockerfile: server/Dockerfile
    env_file:
      - ../server/.env
    container_name: server
    command: 
      gunicorn --bind 0.0.0.0:5000 --workers 4 --pythonpath /var/www/ "server.src.app:main()"    
    volumes:
      - ../server:/var/www/server
    expose:
      - "5000"
    ports:
      - 5000
    networks:
      my-network:
        aliases:
          - server

networks:
  my-network:
