# upstream api {
#     server api:5000;
# }

# upstream client {
#     server client:3000;
# }

# server {
#     listen 80;
#     server_name _;
#     error_log /var/log/nginx/project_error.log;
#     access_log /var/log/nginx/project_access.log;
    

#   location / {
#     proxy_pass http://client;
#     proxy_set_header Host $http_host;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#     proxy_redirect off;
#     proxy_buffering off;
#   }

#     location ~ /api/v1/ {
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header Host $http_host;
#         proxy_buffering off;
#         proxy_redirect off;
#         proxy_pass http://api;
#     }
# }
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost 127.0.0.1;

        location / {
            proxy_pass http://192.168.56.1:3000;
        }

        location ~ /api/v1 {
            proxy_pass http://192.168.56.1:5000/api/v1;
        }
    }
}